---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - flake8 ./certbot_dns_corenetworks
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python27
  image: python:2.7
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest tests --cov=certbot_dns_corenetworks --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python35
  image: python:3.5
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest tests --cov=certbot_dns_corenetworks --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python36
  image: python:3.6
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest tests --cov=certbot_dns_corenetworks --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python37
  image: python:3.7
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest tests --cov=certbot_dns_corenetworks --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python38
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - pytest tests --cov=certbot_dns_corenetworks --no-cov-on-fail
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: codecov
  image: python:3.8
  commands:
  - pip install codecov -qq
  - codecov --required -X gcov
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    PY_COLORS: 1
  depends_on:
  - python27
  - python35
  - python36
  - python37
  - python38

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- lint

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.8
  commands:
  - pip install -r dev-requirements.txt -qq
  - pip install -qq .
  - bandit -r ./certbot_dns_corenetworks -x ./certbot_dns_corenetworks/test
  environment:
    PY_COLORS: 1

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py sdist bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

image_pull_secrets:
- docker_config

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- build-package

---
kind: signature
hmac: d107c344afb445a597ceee39eeb6ec40de5e7975391e23acd7c2b16d6c006025

...
